
data:
  tickers:
    - MSFT
    - AAPL
    - 2222.SR
    - AMZN 
    - GOOGL
 
  start_date: '2013-01-01'
  end_date: '2023-12-31'
  raw_data_path: 'data/raw/'
  interval: 'daily'
  features: 'Adj Close'





